set notermguicolors
set hidden
set smartcase
set ignorecase
set modeline
set number
set expandtab
set shiftwidth=2
set completeopt=menuone,noinsert,noselect

set nocompatible
filetype plugin indent on
syntax on

let mapleader = ";"
let maplocalleader = mapleader

set modelines=5
set bs=indent,eol,start

" one space after period
set nojoinspaces
" Ignore files when completing
set suffixes+=.class,.pyc,.pyo
set suffixes+=.lo,.swo
" Don't ignore headers when completing
set suffixes-=.h

" show line number and character pos
set ruler
set sts=4
" keep 4 lines above and below the cursor
set so=4

" I always lose the cursor, sigh
set cursorline

" show input commands as they're being typed
set showcmd

set signcolumn=yes

" complete recursively in subdirs
set path+=**
" unexplainable but helpful completion settings
set wildmenu wildmode=list,list:longest
set wildignore+=/.git/**

" always include status line
set laststatus=2

" don't remember options in seccions
set sessionoptions-=options

" don't let search open a fold
" set fdo-=search

" help ins-completion
" C-n, C-p are what to default to

" i have cores for a reason
set makeprg=make\ -j8

" my simple statusline, airline was a steaming pile
set statusline=%q%t                              " filename
set statusline+=\ @\ %P                          " percentage of the way thru file
set statusline+=\ [ft=%Y%M%R%W%H]                " filetype
set statusline+=\ char:0x%B                      " hex of character under cursor
set statusline+=\ pos\ %l:%c                     " line:column position of cursor
set statusline+=\ %{wordcount()['words']}\ words " word count
set statusline+=\ %=%<%{expand('%:~:.:h')}       " directory

" larger command display
set cmdheight=2

"set tags=./tags,./TAGS,tags,TAGS,./.tags,./.TAGS,.tags,.TAGS,../../tags,../tags
let &tags.=expand(",$TAGS")
" R mode customizations
let R_assign = 2

set grepprg=rg\ --vimgrep\ $*
set grepformat=%f:%l:%c:%m

" functions
function s:camel_word(dir)
    call search('\U\zs\u\|\<', a:dir)
endfunction


" Global mappings {{{
" disable keymapping for Ex mode
nnoremap Q <nop>

" one of my habits is to I<type><CR><type> or whatever and this can introduce
" whitespace errors. let's try this.
" nnoremap I<CR> O<Esc>jI

" functions from junegunn-fzf.vim
" each brings up fuzzy completion list
" <Leader>u - list of buffers
nnoremap <Leader>u :Buffers<CR>
" <Leader>f - list of files under the current Git repo
nnoremap <Leader>F :<C-u>GitFiles<CR>
" <Leader>f - list of files under the current directory
nnoremap <Leader>f :<C-u>Files<CR>
" <Leader>f - list of tags
nnoremap <Leader>t :Tags<CR>

" <Leader>d deletes the current buffer
" nnoremap <Leader>d :bd<CR>

" Insert current date into buffer. Used for note taking.
nnoremap <Leader>it "=strftime("%c")<CR>p

" select some text, then type // and it will search for the literal text
vnoremap // y/\V<C-R>"<CR>

" by default, do not highlight search matches
set nohlsearch
" bind kind to turn on highlighting for search matches
nnoremap <Leader>h :set hlsearch! hlsearch?<CR>
" highlight matches in search
" set hlsearch
" CTRL-L turns off highlights
" nnoremap <Leader>h :noh<CR>
"nnoremap <Space> zz

" close the current window
nnoremap <Leader>c <C-w>c
" make the current window the only window
nnoremap <Leader>o <C-w>o
" easier movement in splits taking into account dvorak
" nnoremap <C-h> <C-w><C-h>
" nnoremap <C-t> <C-w>k
" nnoremap <C-n> <C-w>j
" nnoremap <C-s> <C-w><C-l>

" C-w ] will open tag in a split
" C-w g } will let you select tag for preview
nnoremap <C-n> :lua vim.diagnostic.goto_next()<CR>
nnoremap <C-p> :lua vim.diagnostic.goto_prev()<CR>
nnoremap <Leader>n :cnext<CR>
nnoremap <Leader>p :cprev<CR>

" Put timestamp in filename?
cmap <F3> <C-R>=strftime("%Y%m%d%H%M")<CR>

nnoremap <silent> _ :aboveleft sp<CR>:exe "normal \<Plug>VinegarUp"<CR>
nnoremap <silent> <Bar> :aboveleft vsp<CR>:exe "normal \<Plug>VinegarUp"<CR>
" }}}

command CtagsCpp !ctags --c++-kinds=+p --c-kinds=+p --fields=+iaS --extra=+q -Rnu .

command HighlightCurrentLine call matchadd('Search', '\%'.line('.').'l')
command ClearHighlightCurrentLine call clearmatches()

" https://vim.fandom.com/wiki/Search_across_multiple_lines
" Search for the ... arguments separated with whitespace (if no '!'),
" or with non-word characters (if '!' added to command).
function! SearchMultiLine(bang, ...)
  if a:0 > 0
    let sep = (a:bang) ? '\_W\+' : '\_s\+'
    let @/ = join(a:000, sep)
  endif
endfunction
command! -bang -nargs=* -complete=tag S call SearchMultiLine(<bang>0, <f-args>)|normal! /<C-R>/<CR>

" package fzf-vim {{{
" :BuffersDelete function to use fzf to delete buffers
function! s:list_buffers()
    redir => list
    silent ls
    redir END
    return split(list, "\n")
endfunction

function! s:delete_buffers(lines)
    execute 'bwipeout' join(map(a:lines, {_, line -> split(line)[0]}))
endfunction

" Call :BuffersDelete to pop up window of buffers to delete, use tab to
" select a buffer for deletion, enter to delete all
command! BuffersDelete call fzf#run(fzf#wrap({
            \ 'source': s:list_buffers(),
            \ 'sink*': { lines -> s:delete_buffers(lines) },
            \ 'options': '--multi --reverse --bind ctrl-a:select-all+accept'
            \ }))

" https://github.com/junegunn/fzf.vim/issues/556
" remap `gf` to pick up files anywhere inside current directory rather than
" just the literal `<cfile>` when you want the same for some *other*
" directory, you put your cursor on the filename and type `:GF other-dir`
function! GF(...)
    call fzf#run({'dir': a:1, 'source': 'find . -type f', 'options':['-1', '--query', expand('<cfile>')], 'sink': 'e'})
endfunction
command! -nargs=* GF :call GF(<f-args>)

" goto fzf file at cursor
" nnoremap gf :call fzf#vim#files('.', {'options':'-1 --query '.expand('<cword>')})<CR>

" search from cwd
nnoremap \ :Rg<CR>
" fzf over lines in current buffer, :Lines for all buffers
nnoremap <Leader>b :BLines<CR>
nnoremap <Leader>B :Lines<CR>
" }}}

" package vimtex {{{
let g:tex_flavor = "latex"
let g:vimtex_disable_recursive_main_file_detection = 1
" }}}

" GUI options {{{
if has('gui')
    set guioptions-=m " no menu
    set guioptions-=T " no toolbar
    set guioptions-=r " no scrollbars
    set guioptions-=R
    set guioptions-=l
    set guioptions-=L
    set guioptions-=b
    set guifont=Iosevka\ Term\ Medium:h13
    " set guifont=SF\ Mono\ Regular:h13
    " set guifont=Source\ Code\ Pro\ Regular:h13
endif
" }}}

" load all the vim packages now, including pathogen
packloadall

" z3 specific style settings for c++
autocmd BufRead
     \ ~/work/inprogress/z3/*/{src,tools,tests}/*.{cc,cpp,h,inc}
     \ setlocal makeprg=make\ -C\ .vimbuild\ -j24\ all sw=4 cino=:0,l1,g0,t0,(0,w1,W4

" Trailing whitespace
command StripTrailingWhitespace %s/\s\+$//e

" Goyo config {{{
let g:goyo_width = 120

function! s:goyo_enter()
    set lbr
endfunction

function! s:goyo_leave()
    set nolbr
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
" }}}
"
" base16-shell
function! s:base16_customize() abort
  call Base16hi("Comment", g:base16_gui05, g:base16_gui00, g:base16_cterm04, g:base16_cterm00, "", "")
endfunction

augroup on_change_colorschema
  autocmd!
  autocmd ColorScheme * call s:base16_customize()
augroup END

if exists('$BASE16_THEME') && (!exists('g:colors_name') || g:colors_name != 'base16-$BASE16_THEME')
  let base16colorspace=256
  colorscheme base16-$BASE16_THEME
endif

autocmd BufNewFile,BufRead *.dl setfiletype souffle

runtime vimrc_local

